# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Pay-As-You-Go (42df2347-4819-4f20-8061-59dbfc6b58d5)'
    KeyVaultName: 'poc-kv-dev'
    SecretsFilter: '*'
- task: replacetokens@3
  inputs:
    targetFiles: '**/*.properties'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '*{'
    tokenSuffix: '*}'
- task: Maven@3
  inputs:
    options: -Dmaven.test.skip=true
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
